# Generated by Django 4.2.3 on 2023-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
