# Generated by Django 4.2.3 on 2023-07-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
